tasks:
  - init: git remote set-url origin https://manfmexistence:glpat-nwfEdsqX8hX5z6goTVDy@gitlab.com/manfmexistence/friday.git && npm install -g npm@11.4.2 vercel bun && bun install && bun run build
    command: git remote set-url origin https://manfmexistence:glpat-nwfEdsqX8hX5z6goTVDy@gitlab.com/manfmexistence/friday.git && npm install -g npm@11.4.2 vercel bun && bun install && bun dev
